### ISSUE TITLE
A litttle help to clarify something.

### ISSUE THREAD

**Issue by aGIToz** [rflamary/POT#101]
Hello,

I don't have a formal background in OT, therefore pardon me if I am asking something extremely silly. In the plot_ot_1d.py, for the cost matrix calculation : 
`M = ot.dist(x.reshape((n, 1)), x.reshape((n, 1)))`

It is bit strange because I was expecting cost matrix to be something in between two distributions but it seems that cost matrix is rather in between the samples of the 2 distribution. Kindly reply.

**Comment by hichamjanati** [comment]
Hi,
If you're referring to this 

https://github.com/rflamary/POT/blob/b2157e9b3458388571f6ae87d80f47f500dfa166/examples/plot_OT_1D.py#L31-L39

M is computed between the bins, the coordinates of the supports of the distributions, not the samples a and b

**Comment by aGIToz** [comment]
Hello in this [short intro to OT by Remi.](https://remi.flamary.com/demos/transport.html)

I believe the cost matrix C in the article represents the M, right?

Now it clearly says in 2nd paragraph that  **The source and target samples are in matrices Xs=[xs1,…,xsns]⊤∈Rns×d and Xt=[xt1,…,xtns]⊤∈Rns×d** . And it says  **C(i,j)=||xsi−xtj||2**.
Therefore now my understanding is that cost matrix is in between samples of source and target. 

And here in  plot_ot_1d.py, I guess the that two distributions have the same sample space which is 
`x = np.arange(n, dtype=np.float64)`

I hope I am clear

**Comment by hichamjanati** [comment]
Yes. I think I get where the confusion comes from. Say you have two distributions with densities (in practice normalized histograms) mu_s and mu_t. OT computes a distance between mu_s and mu_t regardless of any `samples` following mu_s / mu_t.

If you have data samples following the distributions mu_s and mu_t, the supports are the different values and the histograms mu_s and mu_t are approximated by the counting sums in the tuto.

Or you directly have access to the histogram weights mu_s and mu_t and their support (x) (which is the case in the example, with the weights of gaussian distributions = a and b). 

In my previous comment a and be are weights* not samples.

**Comment by aGIToz** [comment]
Just to get further clarification.

The **p^{s}_i and p^{t}_j** in the Remi's article, the probablility masses are the weights a and b, rigth?

**Comment by hichamjanati** [comment]
Exactly

**Comment by aGIToz** [comment]
Voila! got it
