### ISSUE TITLE
EMD and Sinkhorn

### ISSUE THREAD

**Issue by patrickfrank1** [rflamary/POT#105]
Hi there,

great library :) I have some small questions.

1. I installed the package and ran some simple test, do I understand it right that:

- ot.emd and ot.lp.emd are the same
- ot.emd2 and ot.lp.emd2 are the same
- emd and emd2 use the same underlying algorithm, but one prints the transportation matrix and the other one the distance
- ot.sinkhorn(method='sinkhorn'), ot.bregman.sinkhorn(method='sinkhorn') and ot.bregman.sinkhorn_knopp are the same
- ot.sinkhorn2 and ot.bregman.sinkhorn2(method='sinkhorn') are the same
- sinkhorn(method='sinkhorn') and sinkhorn2 use the same underlying algorithm, but one prints the transportation matrix and the other one the distance?

2. I observed that for solving one transportation problem emd is much faster than sinkhorn, but I actually expected it to be vice versa, that's one reason to use it.... how come?

3. If I'm using ot.gpu.sinkhorn, how could I calculate the distance from the transportation matrix?

Thanks in advance for clarification on these issues.
Best, Patrick

**Comment by rflamary** [comment]
hello @patrickfrank1,

I think most of your questions are answered in the quickstart guide here:
https://pot.readthedocs.io/en/latest/quickstart.html

Point 1 : yes you understand right all the things. 
Point 2:  question 3 in the FAQ in the quickstart guide
Point 3: loss=np.sum(M*T) where T is the output of sinkhorn gives you the OT loss.

**Comment by patrickfrank1** [comment]
Hi @rflamary, thanks for your quick answer.
