### ISSUE TITLE
POT calculate 2D vector EMD distance which have different length.

### ISSUE THREAD

**Issue by jinfagang** [rflamary/POT#11]
How to calculate 2D vector emd distance using POT? etc. I have these 2 vector:

```
[(0, 1), (1, 1), (2, 2), (3, 2), (4, 1), (5, 1)],
[(0, 1), (1, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1)]

distance matrix:
5x6
```
Actually, the 2 vector are words-bag, and distance matrix is the words Euclidean distance, I want using this to calculate Sentence Distance but don't know how to use EMD distance, any help?

**Comment by rflamary** [comment]
Hello,

The followinge example show you how to compute the OT matrix between 2D samples:
https://github.com/rflamary/POT/blob/master/examples/Demo_2D_OT_samples.ipynb

It is not necessary to have a square distance matrix in practice and the code can handle it.
Once you have the OT matrix G the emd distance can be computed by np.sum(G*M).

You can find more information in the documentation and examples.
