### ISSUE TITLE
Cannot install POT on Mac with 'pip install POT'

### ISSUE THREAD

**Issue by GitHberChen** [rflamary/POT#118]
system: MacOS 10.15.1
pip install POT
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting POT
  Downloading http://mirrors.aliyun.com/pypi/packages/4e/23/8aba82a55d40ac8c5f4313c1c51804dcb239ee3761b9789db1b621e43c87/POT-0.6.0.tar.gz (794kB)
     |████████████████████████████████| 798kB 393kB/s 
Requirement already satisfied: numpy in /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages (from POT) (1.18.0)
Requirement already satisfied: scipy in /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages (from POT) (1.1.0)
Requirement already satisfied: cython in /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages (from POT) (0.29.2)
Building wheels for collected packages: POT
  Building wheel for POT (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/chenlinwei/anaconda3/envs/DL3.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-0mnp0bwh --python-tag cp37
       cwd: /private/tmp/pip-install-tfqvon7y/POT/
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/unbalanced.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/plot.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/stochastic.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/datasets.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/dr.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/smooth.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/gromov.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/optim.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  creating build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  creating build/lib.macosx-10.7-x86_64-3.7/ot/lp
  copying ot/lp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
  copying ot/lp/cvx.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
  creating build/lib.macosx-10.7-x86_64-3.7/ot/externals
  copying ot/externals/funcsigs.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
  copying ot/externals/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
  running build_ext
  building 'ot.lp.emd_wrap' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/ot
  creating build/temp.macosx-10.7-x86_64-3.7/ot/lp
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chenlinwei/anaconda3/envs/DL3.7/include -arch x86_64 -I/Users/chenlinwei/anaconda3/envs/DL3.7/include -arch x86_64 -Iot/lp -I/Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include -I/private/tmp/pip-install-tfqvon7y/POT/ot/lp -I/Users/chenlinwei/anaconda3/envs/DL3.7/include/python3.7m -c ot/lp/emd_wrap.cpp -o build/temp.macosx-10.7-x86_64-3.7/ot/lp/emd_wrap.o -O3
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from ot/lp/emd_wrap.cpp:470:
  In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
  /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  In file included from ot/lp/emd_wrap.cpp:473:
  ot/lp/EMD.h:19:10: fatal error: 'iostream' file not found
  #include <iostream>
           ^~~~~~~~~~
  2 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for POT
  Running setup.py clean for POT
Failed to build POT
Installing collected packages: POT
    Running setup.py install for POT ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/chenlinwei/anaconda3/envs/DL3.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-ppjb9tmf/install-record.txt --single-version-externally-managed --compile
         cwd: /private/tmp/pip-install-tfqvon7y/POT/
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/unbalanced.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/plot.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/stochastic.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/datasets.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/dr.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/smooth.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/gromov.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/optim.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    creating build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    creating build/lib.macosx-10.7-x86_64-3.7/ot/lp
    copying ot/lp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
    copying ot/lp/cvx.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
    creating build/lib.macosx-10.7-x86_64-3.7/ot/externals
    copying ot/externals/funcsigs.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
    copying ot/externals/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
    running build_ext
    building 'ot.lp.emd_wrap' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/ot
    creating build/temp.macosx-10.7-x86_64-3.7/ot/lp
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chenlinwei/anaconda3/envs/DL3.7/include -arch x86_64 -I/Users/chenlinwei/anaconda3/envs/DL3.7/include -arch x86_64 -Iot/lp -I/Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include -I/private/tmp/pip-install-tfqvon7y/POT/ot/lp -I/Users/chenlinwei/anaconda3/envs/DL3.7/include/python3.7m -c ot/lp/emd_wrap.cpp -o build/temp.macosx-10.7-x86_64-3.7/ot/lp/emd_wrap.o -O3
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from ot/lp/emd_wrap.cpp:470:
    In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
    /Users/chenlinwei/anaconda3/envs/DL3.7/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    In file included from ot/lp/emd_wrap.cpp:473:
    ot/lp/EMD.h:19:10: fatal error: 'iostream' file not found
    #include <iostream>
             ^~~~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/chenlinwei/anaconda3/envs/DL3.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-tfqvon7y/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-ppjb9tmf/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rflamary** [comment]
Hello,

Note that the preferred installation on macosx is by using anaconda and the forge that has been compiled and tested.

But if you want to install it on macosx you might need an additional parameter as described in #113. To do that you just need to download the source and edit the setup.py.

I don't have a mac so this kind of error can be caught a bit late. @ncourty could you have a look at it (also bug #113 )?

**Comment by rflamary** [comment]
This should be working now since #130
