### ISSUE TITLE
I have successfully installed the POT library (in windows OS), but I have issue with the emd function

### ISSUE THREAD

**Issue by bharathbhushandamodaran** [rflamary/POT#12]
# In the following example, the emd function works well: 
`a =[0.5, 0.5],
b= [0.5, 0.5],
M =[[0., 1.], [1., 0.]]`
` G0 = ot.emd(a,b,M),
   G0 =array([[ 0.5,  0. ],
       [ 0. ,  0.5]])`

# In the below example (failure case), the output of emd function is of zero's
`a = [0.5, 0.5],
b = [0.2, 0.8]`
`G0 = ot.emd(a,b,M)
G0 = array([[ 0.,  0.],
       [ 0.,  0.]])`

# Failure case on the example mentioned in the documentation (Demo_1D_OT.ipynb), again the output of emd is a matrix of zero's (see the figure)
`n=100,
a= ot.datasets.get_1D_gauss(n, m=20, s=5),
b= ot.datasets.get_1D_gauss(n, m=60, s=10),
x=np.arange(n, dtype=np.float64),
M = ot.dist(x.reshape((n,1)), x.reshape((n,1))),
M/=M.max(),
G0=ot.emd(a,b,M)`

`%matplotlib inline,
pl.figure(1),
ot.plot.plot1D_mat(a,b,G0, 'OT Matrix G0'),
pl.show()`
![figure_4](https://user-images.githubusercontent.com/12643715/27222528-dd19143c-528c-11e7-895f-97dd51e2ea76.png)

# Please let me know how to resolve the issue

**Comment by ncourty** [comment]
There is a serious issue behind this. I need to investigate more closely. I will let you know when it is fixed

**Comment by ncourty** [comment]
Ok, bug spotted. I will soon post a corrected version.

**Comment by rflamary** [comment]
Commited in 2f2b710d0005044e004fbfed851aefebbee007f6
