### ISSUE TITLE
Incompatible with pytorch？

### ISSUE THREAD

**Issue by zsfeihua** [rflamary/POT#120]
**Some questions about pytorch and ot**
First, I install pot by conda install -c conda-forge pot.
After this, I try to installl pytorch by conda install pytorch torchvision cudatoolkit=9.0 -c pytorch.
Then, bug comes. It says there's some compatibility issues and begins to check.
As follows,
![批注 2020-01-04 171151](https://user-images.githubusercontent.com/38092047/71763323-b83c4e00-2f15-11ea-98b0-96a9d0756011.png)

I want to know how to solve it?

**Comment by hichamjanati** [comment]
Are you sure this compatibility issue is related to the installation of POT ?

**Comment by zsfeihua** [comment]
> Are you sure this compatibility issue is related to the installation of POT ?

Sorry, my bad.
I make a mistake.
