### ISSUE TITLE
GW gradient confusion

### ISSUE THREAD

**Issue by octavian-ganea** [rflamary/POT#125]
Hi,

I have a confusion about the GW solver. I see that gwggrad contains the constC term which is consistent with prop 2 from http://proceedings.mlr.press/v48/peyre16.pdf. However, when writing the full GW loss, the constC term will appear alone without any T term (e.g. eq 5 of https://people.csail.mit.edu/jsolomon/assets/gw.pdf), so it will cancel when computing the gradient w.r.t. T. Algorithm 1 from https://people.csail.mit.edu/jsolomon/assets/gw.pdf and 10.28 from https://arxiv.org/pdf/1803.00567.pdf do not use this constC term, but peyre16.pdf does use it in proposition 2, as well as in this library. I would appreciate if you could clarify this issue.

Thank you,

**Comment by ncourty** [comment]
Hello,

I believe this behavior is consistent. When writing the optimization problem, one can discard the constC term to get an equivalent optimization 
problem where both arg-minima coincide (arg min full problem = arg min of problem without constC), but the minimum itself still depends 
on constC (min full problem \neq min problem without constC). Computing the gradient wrt. T of problem (4) using eq (6) in http://proceedings.mlr.press/v48/peyre16.pdf <http://proceedings.mlr.press/v48/peyre16.pdf> 
shows the dependence of the gradient to this constC term, hence its use in the gradient computation. 

I hope my explanations were convincing. 

Best regards,

Nicolas Courty

**Comment by octavian-ganea** [comment]
Thanks. Yes, the gradient wrt. T of problem (4) is indeed given by eq (6)  (only for symmetric C and \bar{C} matrices). However, if additionally we use that T is doubly stochastic, the gradient can omit the constC term. But in the end it does not matter as you said because the gradient is used as a cost matrix in a wasserstein problem and constants do not matter anymore.
