### ISSUE TITLE
GPU implementation of unregularized ot.emd solver

### ISSUE THREAD

**Issue by jpgard** [rflamary/POT#131]
Hi, first, thank you for the excellent software!

I was wondering whether there was a way to easily run the `ot.emd` on a GPU. 

Currently, there is only GPU implementation of `ot.sinkhorn` on GPU (as `ot.gpu.sinkhorn`), but according to the documentation, it requires a regularization parameter `reg > 0` (`ot.emd` is equivalent to `reg = 0`). Is there a way to either modify the existing implementation of `ot.sinkhorn` so that it can be used with `reg = 0`, or provide an implementation of `ot.emd`, perhaps as `ot.gpu.emd`?

Any other suggested workarounds would also be appreciated.

**Comment by ncourty** [comment]
Hello @jpgard , there is currently no plan to provide a GPU implementation of `ot.emd` as the corresponding algorithm is hardly amenable to a GPU version, as it does not rely on classical linear algebra tool, and as such would not benefit from possible parallel accelerations. If memory is an issue, I would recommend to turn to stochastic versions of optimal transport, based on the dual formulation of the problem. If speed is an issue, I am afraid that that the problem you are facing is currently an open research subject, as our C++ implementation of EMD is currently one of the fastest available...

**Comment by jpgard** [comment]
Got it. Thank you for the quick reply!
