### ISSUE TITLE
PEP8 cleanup

### ISSUE THREAD

**Issue by agramfort** [rflamary/POT#2]
running pyflakes gives me:

```
$ pyflakes ot/*/*.py ot/*.py examples/*.py
ot/optim.py:9: '.bregman.sinkhorn_stabilized' imported but unused
ot/utils.py:96: undefined name 'reduce'
examples/demo_OTDA_classes.py:6: 'numpy as np' imported but unused
examples/demo_barycenter_1D.py:12: 'mpl_toolkits.mplot3d.Axes3D' imported but unused
examples/demo_barycenter_1D.py:14: 'matplotlib.colors.colorConverter' imported but unused
```

when running flake8

```
$ flake8 ot/*/*.py ot/*.py examples/*.py
```

you'll see that you have a lot of pep8 style violations.

**Comment by rflamary** [comment]
Hello, pyflakes errors have been corrected in commit https://github.com/rflamary/POT/commit/e2733d354c87bdc3cbc58a5e3e838e688fafe627.

pep8 needs much more work and will be addressed in the future.

**Comment by agramfort** [comment]
thanks for the quick fix !
