### ISSUE TITLE
OT.sinkhorn, error when an input array contain zeros

### ISSUE THREAD

**Issue by jpchev** [rflamary/POT#34]
I'm getting the following error
Warning: numerical errors at iteration 0
when calling 
d_sinkhorn = ot.sinkhorn2(v1, v2, cm, reg)
and v1 or v2 contain zeros.

How to handle this case?
Thanks

**Comment by ncourty** [comment]
Hello @jpchev 
It seems that the regularization value reg is too low and yields numerical errors. Try higher values. 
While the zero values from v1 and v2 should not be a problem, you can try to remove them for efficiency purpose. See this comment on this topic : 
https://github.com/rflamary/POT/issues/30#issuecomment-328535299
