### ISSUE TITLE
remove import plot from ot/__init__.py

### ISSUE THREAD

**Issue by Slasnista** [rflamary/POT#35]
Hello,

Would it be possible to remove line 19 `from . import plot` from ot/__init__.py ?

It automatically loads matplotlib which could generates an error when using an instance without graphical display. 

Thanks in advance !

**Comment by agramfort** [comment]
that's exactly why sklearn has no hard dependency on matplotlib

**Comment by rflamary** [comment]
Agreed,

@Slasnista  feel free to do a PR with the working tests and updated examples (some of them require ot.plot).

**Comment by rflamary** [comment]
Issue has been fixed in PR #41
