### ISSUE TITLE
Displacement interpolation?

### ISSUE THREAD

**Issue by t-vi** [rflamary/POT#37]
Hello,

thank you for POT!
In the [1] reference, the interpolation is discussed and an example given (see link below).
Is it feasible to do this in POT (the matlab code is https://github.com/gpeyre/2013-SIIMS-ot-splitting ) or to extend POT to do it?

Best regards

Thomas

**Comment by rflamary** [comment]
Hello Thomas,

Sorry for the late anwser. In practice, if you seign a cots matrix C that encode the manifold off the data (with distance as shorttest path on graph of pixels) you can do the dipslacement interpolation using the barycenter function (regularized with entropy).

I think that you will have numerical problems in practice but it should work for a reasonable sampling.

For the moment though i would recommend to use the proximal method algorithm (that have a c and matlab implementation).

Keep us in mind if you implement it and feel free to contribute to POT.
