### ISSUE TITLE
Feature request:- convolution Wasserstein distances

### ISSUE THREAD

**Issue by kowshikthopalli** [rflamary/POT#51]
Hi, I wish to request to add the code from the paper- http://people.csail.mit.edu/jsolomon/assets/convolutional_w2.compressed.pdf 
Their matlab code is here https://github.com/gpeyre/2015-SIGGRAPH-convolutional-ot.git

Thanks 
Kowshik

**Comment by rflamary** [comment]
added the feature in PR #64
