### ISSUE TITLE
UnicodeDecodeError: 'ascii' while installing with pip

### ISSUE THREAD

**Issue by rodrigorivera** [rflamary/POT#55]
Hi everyone,

I am trying to install POT on an Ubuntu 16.04 with Anaconda and

- Python 3.6
- Cython 0.28.3
- Numpy 1.14.5
- Scipy 1.1.0
- Matplotlib 2.2.2

using the instructions on http://pot.readthedocs.io/en/stable/

When executing `pip install POT`, I obtain the following error message.

`
    Collecting pot
      Using cached https://files.pythonhosted.org/packages/50/66/714ee432a02e95a869c8e243e369ebad60e69a72ab1a72367c31df206619/POT-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-4awvn1uv/pot/setup.py", line 26, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4awvn1uv/pot/setup.py", line 29, in <module>
        README = open(os.path.join(ROOT, 'README.md')).read()
      File "/root/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5501: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4awvn1uv/pot/
`

However, if I do `conda install -c conda-forge pot`, it updates

- ca-certificates
- certifi
- conda
- openssl

and then it installs successfully POT.

I have installed POT on OSX with pip successfully with a similar anaconda setup.

**Comment by rflamary** [comment]
Hello and thank you for this bug report.

The setup.py file has been changed quite a bit (proper open with codec and removed pypandoc) in master from 0.4 and should not have problems now.
https://github.com/rflamary/POT/blob/master/setup.py
If you want to try and install the master (quite stable with numerous tests) version you can dot ```pip install .``` from the POT repo.

We will do a 0.5 release shortly  as soon as some PR are merged.

**Comment by rodrigorivera** [comment]
It works as you described. Thank you. I will close the issue now.
