### ISSUE TITLE
GENERALIZED  CONDITIONAL  GRADIENT FOR SOLVING REGULARIZED OT PROBLEMS

### ISSUE THREAD

**Issue by ycui123** [rflamary/POT#69]
Could you please tell me where is the solver for GCG? I've been searched for a while but couldn't find it. Thank you

**Comment by ncourty** [comment]
It is located in the optim.py module.
https://github.com/rflamary/POT/blob/d4847a8c52c09319d751e2c7d29617398b08bae7/ot/optim.py#L207
