### ISSUE TITLE
Improve typos in Notebooks

### ISSUE THREAD

**Issue by vfdev-5** [rflamary/POT#77]
Hi,
Probably a minor copy/paste fix needed in the notebooks:
- https://github.com/rflamary/POT/blob/master/notebooks/plot_otda_mapping_colors_images.ipynb
- https://github.com/rflamary/POT/blob/master/notebooks/plot_otda_color_images.ipynb

For example, in the latter, the following code seems produce EMD instead of Sinknorn
```python
# prediction between images (using out of sample prediction as in [6])
transp_Xs_emd = ot_emd.transform(Xs=X1)
transp_Xt_emd = ot_emd.inverse_transform(Xt=X2)

transp_Xs_sinkhorn = ot_emd.transform(Xs=X1) # Shouldn't be ot_sinkhorn.transform(Xs=X1) ?
transp_Xt_sinkhorn = ot_emd.inverse_transform(Xt=X2)  # Same here
```
At least, it would match the example:
https://github.com/rflamary/POT/blob/e757b75976ece1e6e53e655852b9f8863e7b6f5a/examples/plot_otda_color_images.py#L118-L119

Thanks
PS. Sorry if I misunderstood something.

**Comment by rflamary** [comment]
Indeed this is a typo, thank you for noticing.

Since the notebooks are generated automatically from the example we only need to the corresponding examples in the example folder.

You are welcome to provide a PR.

**Comment by vfdev-5** [comment]
@rflamary sure, I can send a PR. However I have no idea on how to regenerate the notebooks.
Actually, `plot_otda_color_images.ipynb` was not regenerated since the edits of `plot_otda_color_images.py` as they differ too.

**Comment by rflamary** [comment]
OK I can do it no problem.

For your information, the notebooks/doc can be updated by executing the script `nb_build` in folder `POT/docs/`.  It takes a lot of time and memory the first time so don't worry about it.

Thank you again.
