### ISSUE TITLE
Docstring issues in ot.da

### ISSUE THREAD

**Issue by ngayraud** [rflamary/POT#83]
There are some docstring inconsistencies in the docstring of some classes such as the Sinkhorn class: the parameter mapping is not in the signature call, so, how does one control the mapping now? there is an "out_of_sample_map" parameter in the call upon class construction which should be explained in the docstring of these classes. 

Example:

Init signature: SinkhornLpl1Transport(reg_e=1.0, reg_cl=0.1, max_iter=10, max_inner_iter=200, log=False, tol=1e-08, verbose=False, metric='sqeuclidean', norm=None, distribution_estimation=<function distribution_estimation_uniform at 0x7effd9dd6400>, **out_of_sample_map**='ferradans', limit_max=inf)
Docstring:     
Domain Adapatation OT method based on sinkhorn algorithm +
LpL1 class regularization.

Parameters
----------
reg_e : float, optional (default=1)
    Entropic regularization parameter
reg_cl : float, optional (default=0.1)
    Class regularization parameter
**mapping** : string, optional (default="barycentric")
    The kind of mapping to apply to transport samples from a domain into
    another one.
    if "barycentric" only the samples used to estimate the coupling can
    be transported from a domain to another one.
metric : string, optional (default="sqeuclidean")
    The ground metric for the Wasserstein problem
norm : string, optional (default=None)
    If given, normalize the ground metric to avoid numerical errors that
    can occur with large metric values.

**Comment by rflamary** [comment]
Hello @ngayraud and thank you for reporting the issue

Could you please do a quick PR for that?

**Comment by ngayraud** [comment]
Sure. I have to see how the mapping is controlled I'm the code first. Is
there still a choice between barycentric and out of sample? Is it
controlled by that parameter?

Le ven. 10 mai 2019 à 07:01, Rémi Flamary <notifications@github.com> a
écrit :

**Comment by rflamary** [comment]
From a quick look at the code:
https://github.com/rflamary/POT/blob/master/ot/da.py#L967
 it seems that in practice it is controled mostly by if the provided Xs or Xt are the same as the one used for fitting so barycentric mapping in this case or out of samples from barycentric mapping on new data.

From what i remember from the original discussions this parameter was added in the case some other mapping were implemented which seems was never done ;).

**Comment by ngayraud** [comment]
Ok I'll make a PR for it, thanks!

Le ven. 10 mai 2019 à 08:55, Rémi Flamary <notifications@github.com> a
écrit :

**Comment by rflamary** [comment]
Fixed in PR #84
