### ISSUE TITLE
Cannot run gpu modules

### ISSUE THREAD

**Issue by agosztolai** [rflamary/POT#85]
Hello, 

I am trying out the GPU implementation of the sinkhorn transport, but with not much success.

```
>>> a=[.5,.5]
>>> b=[.5,.5]
>>> M=[[0.,1.],[1.,0.]]
>>> ot.gpu.sinkhorn(a,b,M,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ot' has no attribute 'gpu'
```

However, the ot.sinkhorn(a,b,M,1) works as expected.
I have cupy installed as well as the CUDA SDK. 

Could someone help?

**Comment by rflamary** [comment]
Hello,

The gpu module is not imported by default to avoid errors when people do not have cupy installed.

You have to do ```import ot.gpu``` before using the functions

**Comment by agosztolai** [comment]
Thank you and also for making this package.

Have you made effort to implement it for a batch of Wasserstein distances?

Best wishes, 

Adam

**Comment by rflamary** [comment]
Hello,

Actually the current sinkhorn (and sinkhorn on gpu) implementations shoud work in a one-to-may configuration if b is a matrix (list of distribution). In this case it only returns the distance due to memory limits. But in this case you need to have the same distance matrix for each pair.

You are welcome to contribute on the toolbox if you implement more efficient computation on batches ;).

For a short term we definitely need a better documentation for the gpu implementations and a clear list of submodules that are automatically imported. 

Rémi

**Comment by patrickfrank1** [comment]
I tried to use the gpu version for the one-to-many configuration like this:

```python
import numpy as np
import ot
import ot.gpu

sinkhorn_distance = np.zeros((50,50))

elements = np.random.random((1000,100)) #underlying population
d = ot.gpu.dist(elements,metric='euclidean') #pairwise distance

np.random.seed(42)
weights = np.random.randint(low=0,high=10,size=(1000,50)).astype(np.float)
#print(weights[:,0])

for j in range(50):
    sum_col = sum(weights[:,j])
    for i in range(1000):
        weights[i,j] = 1.0*weights[i,j]/sum_col

#print(sum(weights[:,0]),weights[:,0]) #columns normalized to 1

for j in range(50):
    print(weights[:,j].shape, weights.shape, d.shape)
    m = ot.gpu.sinkhorn(weights[j], weights, d, 9)
    sinkhorn_distance[j,:] = m
```

where `weights[j]` is one weight vector with dimension (1000,) and `weights` is a bunch of weight vectors with dimension (1000,50).

However I get the error `ValueError: operands could not be broadcast together with shapes (50, 1), (1000, 1000)`, what am I misunderstanding?

Best,
Patrick

**Comment by rflamary** [comment]
Hello Patrick

weights[j] returns the line j and not column j so you don't have the right shape, you should have weights[:,j] in the last loop. This has nothing to do with gpu module.

Note that this kind of question is better posed on the mailing list since it is not a bug of POT.
