### ISSUE TITLE
Free support barycenter examples

### ISSUE THREAD

**Issue by kilianFatras** [rflamary/POT#96]
Hello,

I have been working on your free support barycenter examples. 
https://github.com/rflamary/POT/blob/master/examples/plot_free_support_barycenter.py

I went through the code and there is something which looks wrong to me. To plot your figure you used : 

for (x_i, b_i) in zip(measures_locations, measures_weights):
    color = np.random.randint(low=1, high=10 * N)
    pl.scatter(x_i[:, 0], x_i[:, 1], s=b * 1000, label='input measure')

but I think it should be $s=b_i * 1000$ instead of $s=b * 1000$.

I can make a PR to correct it if it is a mistake.

**Comment by rflamary** [comment]
ideed it looks fishy

Please correct in a PR if it looks better afterards ;)

**Comment by rflamary** [comment]
Fixed in PR #98
